server:
 port: 8080
 address: 127.0.0.1

spring:
 datasource:
  username: root
  password: 12345678
  url: jdbc:mysql://127.0.0.1:3306/finData?characterEncoding=utf-8
  driver-class-name: com.mysql.cj.jdbc.Driver

 devtools:
  restart:
   enabled: true
   additional-paths: src/main/java

mybatis:
 mapper-locations: classpath:/mapper/*.xml
